### POST A BLOG !
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2EiLCJpZCI6IjVlZjZmNDk2MGQwMzU2NDU3OGQ1MDk2NyIsImlhdCI6MTU5MzI3NTA5N30.eJ6UtMgeueCzeTkf0QCDaFNif_O_CetV3b1zUmwf4qw

{
    "title": "TokenBlog",
    "author": "Mika",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 2
}
###
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhYXZpIiwiaWQiOiI1ZWY3YmFhMTJhMjRhMzBhNTRjZDNhNTMiLCJpYXQiOjE1OTMyOTM0OTR9.ssLY6gW9lGAvtccdKXf2mrprg5DExUP8qFCVRg05uUw

{
    "title": "Testiblog",
    "author": "Jouko",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 6
}
###
DELETE http://localhost:3001/api/blogs/5f1c37c47425904b2cce2166
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2EiLCJpZCI6IjVlZjZmNDk2MGQwMzU2NDU3OGQ1MDk2NyIsImlhdCI6MTU5NTY4NjAxMX0.wrotzlU0-oJnfD0PnOP3Bo2L7BhBx3Yp-ag_a4Vb9Fc

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Mika Leppiaho",
    "username": "mika",
    "password": "salasana"
    
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Taavi Testaaja",
    "username": "taavi",
    "password": "salasana"
    
}


###
GET http://localhost:3003/api/blogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2EiLCJpZCI6IjVlZjZmNDk2MGQwMzU2NDU3OGQ1MDk2NyIsImlhdCI6MTU5MzI3NTA5N30.eJ6UtMgeueCzeTkf0QCDaFNif_O_CetV3b1zUmwf4qa

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mika",
    "password": "salasana"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "taavi",
    "password": "salasana"
}